  
#ifndef _COMMANDS_H
#define _COMMANDS_H

 const char new_line= '\n';

/********************************************
 * ADC COMMANDS
 * ******************************************/
#define FETCH_ADC0 "CROSS+ADC0"
#define FETCH_ADC1 "CROSS+ADC1"
#define FETCH_ADC2 "CROSS+ADC2"
#define FETCH_ADC3 "CROSS+ADC3"
#define FETCH_ADC4 "CROSS+ADC4"
#define FETCH_ADC5 "CROSS+ADC5"
#define FETCH_ADC6 "CROSS+ADC6"
#define FETCH_ADC7 "CROSS+ADC7"
#define FETCH_ADC8 "CROSS+ADC8"
#define FETCH_ADC9 "CROSS+ADC9"
#define FETCH_ADC10 "CROSS+ADC10"
#define FETCH_ADC11 "CROSS+ADC11"
#define FETCH_ADC12 "CROSS+ADC12"
#define FETCH_ADC13 "CROSS+ADC13"
#define FETCH_ADC14 "CROSS+ADC14"
#define FETCH_ADC15 "CROSS+ADC15"


/********************************************
 * GPIO COMMANDS
 * ******************************************/
//INPUT COMMANDS
#define PINA0_INPUT "CROSS+INPUT_A0"
#define PINA1_INPUT "CROSS+INPUT_A1"
#define PINA2_INPUT "CROSS+INPUT_A2"
#define PINA3_INPUT "CROSS+INPUT_A3"
#define PINA4_INPUT "CROSS+INPUT_A4"
#define PINA5_INPUT "CROSS+INPUT_A5"
#define PINA6_INPUT "CROSS+INPUT_A6"
#define PINA7_INPUT "CROSS+INPUT_A7"

#define PINB0_INPUT "CROSS+INPUT_B0"
#define PINB1_INPUT "CROSS+INPUT_B1"
#define PINB2_INPUT "CROSS+INPUT_B2"
#define PINB3_INPUT "CROSS+INPUT_B3"
#define PINB4_INPUT "CROSS+INPUT_B4"
#define PINB5_INPUT "CROSS+INPUT_B5"
#define PINB6_INPUT "CROSS+INPUT_B6"
#define PINB7_INPUT "CROSS+INPUT_B7"

#define PINC0_INPUT "CROSS+INPUT_C0"
#define PINC1_INPUT "CROSS+INPUT_C1"
#define PINC2_INPUT "CROSS+INPUT_C2"
#define PINC3_INPUT "CROSS+INPUT_C3"
#define PINC4_INPUT "CROSS+INPUT_C4"
#define PINC5_INPUT "CROSS+INPUT_C5"
#define PINC6_INPUT "CROSS+INPUT_C6"
#define PINC7_INPUT "CROSS+INPUT_C7"

#define PINA0_INPUT "CROSS+INPUT_D0"
#define PINA1_INPUT "CROSS+INPUT_D1"
#define PINA2_INPUT "CROSS+INPUT_D2"
#define PINA3_INPUT "CROSS+INPUT_D3"
#define PINA4_INPUT "CROSS+INPUT_D4"
#define PINA5_INPUT "CROSS+INPUT_D5"
#define PINA6_INPUT "CROSS+INPUT_D6"
#define PINA7_INPUT "CROSS+INPUT_D7"

//OUTPUT COMMANDS
#define PINA0_OUTPUT "CROSS+OUTPUT_A0"
#define PINA1_OUTPUT "CROSS+OUTPUT_A1"
#define PINA2_OUTPUT "CROSS+OUTPUT_A2"
#define PINA3_OUTPUT "CROSS+OUTPUT_A3"
#define PINA4_OUTPUT "CROSS+OUTPUT_A4"
#define PINA5_OUTPUT "CROSS+OUTPUT_A5"
#define PINA6_OUTPUT "CROSS+OUTPUT_A6"
#define PINA7_OUTPUT "CROSS+OUTPUT_A7"

#define PINB0_OUTPUT "CROSS+OUTPUT_B0"
#define PINB1_OUTPUT "CROSS+OUTPUT_B1"
#define PINB2_OUTPUT "CROSS+OUTPUT_B2"
#define PINB3_OUTPUT "CROSS+OUTPUT_B3"
#define PINB4_OUTPUT "CROSS+OUTPUT_B4"
#define PINB5_OUTPUT "CROSS+OUTPUT_B5"
#define PINB6_OUTPUT "CROSS+OUTPUT_B6"
#define PINB7_OUTPUT "CROSS+OUTPUT_B7"

#define PINC0_OUTPUT "CROSS+OUTPUT_C0"
#define PINC1_OUTPUT "CROSS+OUTPUT_C1"
#define PINC2_OUTPUT "CROSS+OUTPUT_C2"
#define PINC3_OUTPUT "CROSS+OUTPUT_C3"
#define PINC4_OUTPUT "CROSS+OUTPUT_C4"
#define PINC5_OUTPUT "CROSS+OUTPUT_C5"
#define PINC6_OUTPUT "CROSS+OUTPUT_C6"
#define PINC7_OUTPUT "CROSS+OUTPUT_C7"

#define PINA0_OUTPUT "CROSS+OUTPUT_D0"
#define PINA1_OUTPUT "CROSS+OUTPUT_D1"
#define PINA2_OUTPUT "CROSS+OUTPUT_D2"
#define PINA3_OUTPUT "CROSS+OUTPUT_D3"
#define PINA4_OUTPUT "CROSS+OUTPUT_D4"
#define PINA5_OUTPUT "CROSS+OUTPUT_D5"
#define PINA6_OUTPUT "CROSS+OUTPUT_D6"
#define PINA7_OUTPUT "CROSS+OUTPUT_D7"




#endif //_COMMANDS_H